### ISSUE TITLE
[Windows] BCU erroneously shows multiple boards when a serial connection is open.

### ISSUE THREAD

**Issue by frhuelsz** [NXPmicro/bcu#10]
**Platform:** Windows 11
**Boards tested:** IMX8ULP
**BCU version:** bcu_1.1.52-0-g17ab144
**FTDI Driver Version:** 2.12.36.4

Steps to reproduce:

1. Connect board FTDI interface to host PC.
2. Verify that the expected "USB Serial Port" devices show up in device manager. (4 for the 8ULP)
<img width="250" alt="image" src="https://user-images.githubusercontent.com/97629030/173452632-c41a5a7c-6b91-414b-889b-a16d9d38699b.png">

3. Run `bcu lsftdi`. Only one board is detected, as expected:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/97629030/173451804-cdf0b374-5c70-41ce-b160-48f552fbe177.png">

4. Open any of the serial devices in any serial console software (Putty, CoolTerm, etc.)
5. Re-run `bcu lsftdi`, 2 boards show up now:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/97629030/173452076-dcf2cfc5-aacb-4870-9c2a-92b83f4dfd73.png">

On the 8ULP, connecting to the first detected COM port (COM15 in this case) causes BCU to fail fetching the location_id:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/97629030/173452253-5290c7a1-9e96-4c51-8d76-6c2e334db534.png">

**Comment by wangxiaoningnxp** [comment]
Hi,
Thank you very much for your report!
I can reproduce this issue.
Will try to fix it.

**Comment by wangxiaoningnxp** [comment]
Fixed this issue with following commit. Please have a try.

commit 5349ba4ef11ea82a25fec69682d0bf0edbc7c805
Author: Clark Wang <xiaoning.wang@nxp.com>
Date:   Tue Jun 14 10:40:04 2022 +0800

    fix incorrect device list when open port with putty on Windows
    
    When any port of FTDI is opened, FT_get_device_info_detail() cannot get
    the information of this port.
    When the port A information cannot be obtained, try to use the port of
    the B/C/D to infer the id of the port A
    
    So here is a limitation. If open all 4 ports are opened with putty, BCU
    cannot get the board id.
    
    Signed-off-by: Clark Wang <xiaoning.wang@nxp.com>
